import AsyncStorage from "@react-native-async-storage/async-storage";
import * as SQLite from "expo-sqlite";
import { Platform } from "react-native";
import type { CachedInventoryRecord, MobileInventorySnapshot, PendingInventoryMutation, RecordCountInput, StoredInventorySnapshot } from "./domain";

const STATE_KEY = "assetx.inventory.mobile.v1";
let databasePromise: Promise<SQLite.SQLiteDatabase> | null = null;
interface OfflineState { version: 1; snapshots: Record<string, StoredInventorySnapshot>; pending: PendingInventoryMutation[]; }
const emptyState = (): OfflineState => ({ version: 1, snapshots: {}, pending: [] });
async function getDatabase() { if (!databasePromise) databasePromise = (async () => { const database = await SQLite.openDatabaseAsync("assetx-mobile.db"); await database.execAsync("CREATE TABLE IF NOT EXISTS mobile_state (state_key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL)"); return database; })(); return databasePromise; }
function normalizeState(value: unknown): OfflineState { if (!value || typeof value !== "object") return emptyState(); const state = value as Partial<OfflineState>; return state.version === 1 && state.snapshots && Array.isArray(state.pending) ? { version: 1, snapshots: state.snapshots, pending: state.pending } : emptyState(); }
async function loadState(): Promise<OfflineState> { try { if (Platform.OS === "web") { const value = await AsyncStorage.getItem(STATE_KEY); return value ? normalizeState(JSON.parse(value)) : emptyState(); } const row = await (await getDatabase()).getFirstAsync<{ value: string }>("SELECT value FROM mobile_state WHERE state_key = ?", [STATE_KEY]); return row?.value ? normalizeState(JSON.parse(row.value)) : emptyState(); } catch { return emptyState(); } }
async function saveState(state: OfflineState) { const value = JSON.stringify(state); if (Platform.OS === "web") return AsyncStorage.setItem(STATE_KEY, value); await (await getDatabase()).runAsync("INSERT INTO mobile_state (state_key, value) VALUES (?, ?) ON CONFLICT(state_key) DO UPDATE SET value = excluded.value", [STATE_KEY, value]); }
const mutationId = () => typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `inventory-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export async function getStoredSnapshot(cycleId: string) { return (await loadState()).snapshots[cycleId] ?? null; }
export async function listStoredSnapshots() { return Object.values((await loadState()).snapshots).sort((a, b) => b.downloaded_at.localeCompare(a.downloaded_at)); }
export async function saveStoredSnapshot(snapshot: MobileInventorySnapshot): Promise<StoredInventorySnapshot> {
  const state = await loadState(); const previous = state.snapshots[snapshot.cycle.id]; const pendingIds = new Set(state.pending.filter((mutation) => mutation.cycle_id === snapshot.cycle.id).map((mutation) => mutation.record_id)); const previousRecords = new Map(previous?.records.map((record) => [record.record_id, record]) ?? []);
  const stored: StoredInventorySnapshot = { cycle: snapshot.cycle, cycle_id: snapshot.cycle.id, downloaded_at: new Date().toISOString(), records: snapshot.records.map((record) => { const oldRecord = previousRecords.get(record.record_id); if (!oldRecord || !pendingIds.has(record.record_id)) return { ...record, sync_state: "synced", local_updated_at: null }; return { ...record, actual_location_id: oldRecord.actual_location_id, actual_location: oldRecord.actual_location, actual_quantity: oldRecord.actual_quantity, actual_status_id: oldRecord.actual_status_id, actual_employee_id: oldRecord.actual_employee_id, inventory_date: oldRecord.inventory_date, notes: oldRecord.notes, is_verified: false, sync_state: "pending", local_updated_at: oldRecord.local_updated_at }; }) };
  state.snapshots[snapshot.cycle.id] = stored; await saveState(state); return stored;
}
export async function listPendingMutations(cycleId?: string) { const pending = (await loadState()).pending; return cycleId ? pending.filter((mutation) => mutation.cycle_id === cycleId) : pending; }
export async function queueInventoryMutation(cycleId: string, recordId: string, payload: RecordCountInput): Promise<CachedInventoryRecord> {
  const state = await loadState(); const snapshot = state.snapshots[cycleId]; const record = snapshot?.records.find((item) => item.record_id === recordId); if (!snapshot || !record) throw new Error("LOCAL_RECORD_NOT_FOUND"); const existingIndex = state.pending.findIndex((item) => item.cycle_id === cycleId && item.record_id === recordId); const existing = existingIndex >= 0 ? state.pending[existingIndex] : null;
  const mutation: PendingInventoryMutation = { id: existing?.id ?? mutationId(), cycle_id: cycleId, record_id: recordId, asset_id: record.asset_id, mode: existing?.mode === "record" || record.actual_quantity === null ? "record" : "update", payload, base_updated_at: existing?.base_updated_at ?? record.updated_at, queued_at: existing?.queued_at ?? new Date().toISOString(), attempts: 0, last_error: null };
  if (existingIndex >= 0) state.pending.splice(existingIndex, 1, mutation); else state.pending.push(mutation); const now = new Date().toISOString(); if (Object.prototype.hasOwnProperty.call(payload, "actual_quantity")) record.actual_quantity = payload.actual_quantity ?? null; if (Object.prototype.hasOwnProperty.call(payload, "actual_location_id")) record.actual_location_id = payload.actual_location_id ?? null; if (Object.prototype.hasOwnProperty.call(payload, "notes")) record.notes = payload.notes ?? null; record.inventory_date = now; record.is_verified = false; record.sync_state = "pending"; record.local_updated_at = now; await saveState(state); return record;
}
export async function markMutationSynced(mutationIdValue: string, recordId: string, cycleId: string, updatedAt?: string) { const state = await loadState(); state.pending = state.pending.filter((item) => item.id !== mutationIdValue); const record = state.snapshots[cycleId]?.records.find((item) => item.record_id === recordId); if (record) { record.sync_state = "synced"; record.local_updated_at = null; if (updatedAt) record.updated_at = updatedAt; } await saveState(state); }
export async function markMutationConflict(mutationIdValue: string, recordId: string, cycleId: string) { const state = await loadState(); state.pending = state.pending.filter((item) => item.id !== mutationIdValue); const record = state.snapshots[cycleId]?.records.find((item) => item.record_id === recordId); if (record) { record.sync_state = "conflict"; record.local_updated_at = new Date().toISOString(); } await saveState(state); }
export async function registerMutationFailure(mutationIdValue: string, code?: string) { const state = await loadState(); const mutation = state.pending.find((item) => item.id === mutationIdValue); if (!mutation) return null; mutation.attempts += 1; mutation.last_error = code ?? "SYNC_FAILED"; await saveState(state); return mutation; }
export async function clearOfflineInventory() { if (Platform.OS === "web") return AsyncStorage.removeItem(STATE_KEY); await (await getDatabase()).runAsync("DELETE FROM mobile_state WHERE state_key = ?", [STATE_KEY]); }
