import { useCallback, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { AppScreen, Card, PageHeader, PrimaryButton, SecondaryButton, StatusBadge, colors } from "@/components/mobile-ui";
import { type CachedInventoryRecord } from "@/features/assetx/domain";
import { getStoredSnapshot, queueInventoryMutation } from "@/features/assetx/offline-store";

export default function RecordScreen() {
  const router = useRouter(); const { cycleId, recordId } = useLocalSearchParams<{ cycleId: string; recordId: string }>(); const [record, setRecord] = useState<CachedInventoryRecord | null>(null); const [quantity, setQuantity] = useState(""); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false);
  const refresh = useCallback(async () => { const item = (await getStoredSnapshot(String(cycleId)))?.records.find((value) => value.record_id === String(recordId)) ?? null; setRecord(item); if (item) { setQuantity(String(item.actual_quantity ?? item.expected_quantity ?? 1)); setNotes(item.notes ?? ""); } }, [cycleId, recordId]); useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  async function save(actualQuantity: number) { if (!record || !Number.isFinite(actualQuantity) || actualQuantity < 0) return Alert.alert("الكمية غير صحيحة", "أدخل رقماً صفراً أو أكبر."); setSaving(true); try { await queueInventoryMutation(String(cycleId), record.record_id, { actual_quantity: actualQuantity, notes: notes.trim() || null }); router.back(); } catch { Alert.alert("تعذر الحفظ", "تعذر حفظ النتيجة محلياً على الهاتف."); } finally { setSaving(false); } }
  if (!record) return <AppScreen><PageHeader title="تفاصيل الأصل" action={<Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={25} color="#FFFFFF" /></Pressable>} /><View style={styles.missing}><Text style={styles.missingText}>لم يُعثر على هذا السجل في الدورة المحفوظة.</Text></View></AppScreen>;
  const inputQuantity = Number(quantity);
  return <AppScreen scroll><PageHeader title="تفاصيل الأصل" subtitle={record.asset_code} action={<Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={25} color="#FFFFFF" /></Pressable>} /><View style={styles.content}><Card style={styles.card}><StatusBadge label={record.sync_state === "pending" ? "بانتظار المزامنة" : record.sync_state === "conflict" ? "يحتاج مراجعة" : "محفوظ"} tone={record.sync_state === "pending" ? "amber" : record.sync_state === "conflict" ? "red" : "green"} /><Text style={styles.name}>{record.asset_name}</Text><View style={styles.info}><Text style={styles.value}>{record.expected_location_path ?? record.expected_location ?? "غير محدد"}</Text><Text style={styles.label}>الموقع المتوقع</Text></View><View style={styles.info}><Text style={styles.value}>{record.expected_quantity ?? "—"}</Text><Text style={styles.label}>الكمية المتوقعة</Text></View></Card><Card style={styles.card}><Text style={styles.sectionTitle}>نتيجة الجرد</Text><Text style={styles.label}>الكمية الفعلية</Text><TextInput value={quantity} onChangeText={setQuantity} keyboardType="decimal-pad" style={styles.quantity} textAlign="right" /><Text style={styles.label}>ملاحظة ميدانية اختيارية</Text><TextInput value={notes} onChangeText={setNotes} multiline numberOfLines={3} placeholder="مثال: يحتاج مراجعة الموقع قبل إنشاء طلب نقل" placeholderTextColor="#94A3B8" style={styles.notes} textAlign="right" /></Card><PrimaryButton title="حفظ نتيجة الجرد" icon="save" loading={saving} onPress={() => void save(inputQuantity)} /><SecondaryButton title="تحديد موقع فعلي واقتراح نقل" icon="swap-horiz" disabled={saving} onPress={() => router.push(`/inventory/${cycleId}/record/${recordId}/location`)} /><PrimaryButton title="تسجيل الأصل غير موجود" icon="remove-circle-outline" tone="red" disabled={saving} onPress={() => void save(0)} /><Text style={styles.notice}>اقتراح النقل يُرسل بانتظار الاعتماد فقط؛ لا يتغير موقع الأصل الرئيسي تلقائياً من الهاتف.</Text></View></AppScreen>;
}
const styles = StyleSheet.create({ back: { padding: 8 }, content: { padding: 20, gap: 15 }, card: { gap: 11 }, name: { color: colors.slate, fontSize: 20, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, sectionTitle: { color: colors.slate, fontWeight: "900", fontSize: 17, textAlign: "right", writingDirection: "rtl" }, info: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, label: { color: colors.muted, fontSize: 13, fontWeight: "700", textAlign: "right", writingDirection: "rtl" }, value: { flex: 1, color: colors.slate, textAlign: "left", writingDirection: "rtl" }, quantity: { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: 13, paddingHorizontal: 13, color: colors.slate, fontSize: 18 }, notes: { minHeight: 88, borderWidth: 1, borderColor: colors.border, borderRadius: 13, padding: 13, color: colors.slate, textAlignVertical: "top", writingDirection: "rtl" }, notice: { color: colors.muted, fontSize: 12, lineHeight: 19, textAlign: "right", writingDirection: "rtl" }, missing: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20 }, missingText: { color: colors.muted, textAlign: "center", writingDirection: "rtl" } });
