import { useState } from "react";
import { Alert, Image, KeyboardAvoidingView, Platform, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { AppScreen, Card, FormInput, PrimaryButton, colors } from "@/components/mobile-ui";
import { friendlyError } from "@/features/assetx/domain";
import { useSession } from "@/features/assetx/session-context";
export default function LoginScreen() {
  const router = useRouter(); const { backendUrl, signIn, updateBackendUrl } = useSession(); const [serverUrl, setServerUrl] = useState(backendUrl ?? ""); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false);
  async function handleLogin() { setLoading(true); try { if (serverUrl.trim() !== backendUrl) await updateBackendUrl(serverUrl); await signIn(username.trim(), password); router.replace("/field"); } catch (error) { Alert.alert("تعذر تسجيل الدخول", friendlyError(error)); } finally { setLoading(false); } }
  return <AppScreen scroll><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.container}><View style={styles.brand}><Image source={require("../assets/images/icon.png")} style={styles.icon} /><Text style={styles.title}>AssetX Mobile</Text><Text style={styles.subtitle}>الجرد الميداني المتصل بمنصة AssetX</Text></View><Card style={styles.card}><Text style={styles.cardTitle}>تسجيل الدخول</Text><Text style={styles.hint}>في الشبكة المحلية اكتب رابط الجهاز بالشكل http://عنوان-IP:3001، وليس localhost.</Text><FormInput label="رابط Backend" value={serverUrl} onChangeText={setServerUrl} placeholder="http://192.168.x.x:3001" autoCapitalize="none" autoCorrect={false} keyboardType="url" /><FormInput label="اسم المستخدم" value={username} onChangeText={setUsername} placeholder="اسم المستخدم" autoCapitalize="none" autoCorrect={false} /><FormInput label="كلمة المرور" value={password} onChangeText={setPassword} placeholder="كلمة المرور" secureTextEntry /><PrimaryButton title="دخول آمن" icon="login" loading={loading} disabled={!serverUrl.trim() || !username.trim() || !password} onPress={() => void handleLogin()} /></Card><Text style={styles.security}>لا يحتفظ التطبيق بكلمة المرور. تحفظ رموز الجلسة المشفرة على الجهاز فقط.</Text></KeyboardAvoidingView></AppScreen>;
}
const styles = StyleSheet.create({ container: { flex: 1, gap: 22, justifyContent: "center", paddingVertical: 24 }, brand: { alignItems: "center", gap: 7 }, icon: { width: 82, height: 82, borderRadius: 18 }, title: { color: colors.navy, fontSize: 28, fontWeight: "900" }, subtitle: { color: colors.muted, fontSize: 14, writingDirection: "rtl" }, card: { gap: 15 }, cardTitle: { textAlign: "right", color: colors.slate, fontSize: 21, fontWeight: "900", writingDirection: "rtl" }, hint: { color: colors.muted, fontSize: 12, lineHeight: 19, textAlign: "right", writingDirection: "rtl" }, security: { color: colors.muted, textAlign: "center", fontSize: 12, lineHeight: 19, writingDirection: "rtl" } });

