import { useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Haptics from "expo-haptics";
import { CameraView, useCameraPermissions, type BarcodeScanningResult } from "expo-camera";
import { useLocalSearchParams, useRouter } from "expo-router";
import { PrimaryButton, colors } from "@/components/mobile-ui";
import { getStoredSnapshot } from "@/features/assetx/offline-store";
const normalizeCode = (value: string) => value.trim().replace(/\s+/g, "").toLowerCase();
async function signalScanSuccess() { if (Platform.OS !== "web") await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => undefined); }
export default function ScannerScreen() {
  const router = useRouter(); const { cycleId } = useLocalSearchParams<{ cycleId: string }>(); const [permission, requestPermission] = useCameraPermissions(); const [scanned, setScanned] = useState(false); const [message, setMessage] = useState("وجّه الكاميرا إلى رمز الأصل");
  async function handleScan({ data }: BarcodeScanningResult) { if (scanned) return; setScanned(true); const record = (await getStoredSnapshot(String(cycleId)))?.records.find((item) => normalizeCode(item.asset_code) === normalizeCode(data)); if (record) { setMessage(`تم التعرف على ${record.asset_code}`); void signalScanSuccess(); setTimeout(() => router.replace(`/inventory/${cycleId}/record/${record.record_id}`), 300); return; } setMessage("لم يُعثر على هذا الرمز داخل الدورة الحالية."); setTimeout(() => { setScanned(false); setMessage("حاول مسح رمز آخر"); }, 1600); }
  if (!permission) return <View style={styles.loading} />;
  if (!permission.granted) return <View style={styles.permission}><MaterialIcons name="camera-alt" size={44} color={colors.blue} /><Text style={styles.permissionTitle}>نحتاج إلى الكاميرا لمسح رمز الأصل</Text><Text style={styles.permissionText}>لن تُستخدم الكاميرا للتصوير أو رفع الصور في هذه المرحلة.</Text><PrimaryButton title="السماح بالكاميرا" icon="camera-alt" onPress={() => void requestPermission()} /><Pressable onPress={() => router.back()}><Text style={styles.cancel}>إلغاء</Text></Pressable></View>;
  return <View style={styles.container}><CameraView style={StyleSheet.absoluteFillObject} facing="back" barcodeScannerSettings={{ barcodeTypes: ["qr", "code128", "ean13", "ean8", "code39"] }} onBarcodeScanned={scanned ? undefined : handleScan} /><View style={styles.overlay}><Pressable onPress={() => router.back()} style={styles.close}><MaterialIcons name="close" size={25} color="#FFFFFF" /></Pressable><View style={styles.guide} /><View style={styles.message}><MaterialIcons name={scanned && message.startsWith("تم") ? "check-circle" : "qr-code-scanner"} size={20} color="#FFFFFF" /><Text style={styles.messageText}>{message}</Text></View></View></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: "#000000" }, overlay: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 }, close: { position: "absolute", top: 58, right: 24, width: 46, height: 46, borderRadius: 23, backgroundColor: "rgba(15,23,42,0.72)", alignItems: "center", justifyContent: "center" }, guide: { width: "84%", aspectRatio: 1.2, borderWidth: 3, borderColor: "#FFFFFF", borderRadius: 20, backgroundColor: "rgba(255,255,255,0.05)" }, message: { position: "absolute", bottom: 60, left: 24, right: 24, padding: 15, borderRadius: 14, backgroundColor: "rgba(15,23,42,0.88)", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, messageText: { color: "#FFFFFF", textAlign: "center", fontWeight: "700", writingDirection: "rtl" }, permission: { flex: 1, backgroundColor: colors.page, alignItems: "center", justifyContent: "center", padding: 28, gap: 14 }, permissionTitle: { color: colors.slate, fontSize: 21, fontWeight: "900", textAlign: "center", writingDirection: "rtl" }, permissionText: { color: colors.muted, lineHeight: 21, textAlign: "center", writingDirection: "rtl" }, cancel: { color: colors.blue, fontWeight: "800", padding: 12, writingDirection: "rtl" }, loading: { flex: 1, backgroundColor: "#000000" } });
