import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import type { ComponentProps, PropsWithChildren, ReactNode } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps, type ViewStyle } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

export const colors = { navy: "#0B2545", blue: "#2563EB", blueSoft: "#EFF6FF", green: "#16A34A", greenSoft: "#F0FDF4", amber: "#D97706", amberSoft: "#FFFBEB", red: "#DC2626", redSoft: "#FEF2F2", slate: "#0F172A", muted: "#64748B", border: "#E2E8F0", page: "#F8FAFC" };
type IconName = ComponentProps<typeof MaterialIcons>["name"];
export function AppScreen({ children, scroll = false }: PropsWithChildren<{ scroll?: boolean }>) { return <SafeAreaView edges={["top", "left", "right"]} style={styles.screen}>{scroll ? <ScrollView contentContainerStyle={styles.scroll}>{children}</ScrollView> : <View style={styles.fill}>{children}</View>}</SafeAreaView>; }
export function PageHeader({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <View style={styles.header}><View style={styles.headerAction}>{action}</View><View style={styles.headerText}><Text style={styles.headerTitle}>{title}</Text>{subtitle ? <Text style={styles.headerSubtitle}>{subtitle}</Text> : null}</View></View>; }
export function PrimaryButton({ title, onPress, icon, loading, disabled, tone = "blue" }: { title: string; onPress: () => void; icon?: IconName; loading?: boolean; disabled?: boolean; tone?: "blue" | "green" | "red" }) { const backgroundColor = tone === "green" ? colors.green : tone === "red" ? colors.red : colors.blue; return <Pressable disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [styles.primaryButton, { backgroundColor }, (disabled || loading) && styles.disabled, pressed && styles.pressed]}>{loading ? <ActivityIndicator color="#FFFFFF" /> : <>{icon ? <MaterialIcons name={icon} size={21} color="#FFFFFF" /> : null}<Text style={styles.primaryButtonText}>{title}</Text></>}</Pressable>; }
export function SecondaryButton({ title, onPress, icon, disabled }: { title: string; onPress: () => void; icon?: IconName; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.secondaryButton, disabled && styles.disabled, pressed && styles.pressed]}>{icon ? <MaterialIcons name={icon} size={20} color={colors.blue} /> : null}<Text style={styles.secondaryButtonText}>{title}</Text></Pressable>; }
export function FormInput({ label, ...props }: TextInputProps & { label: string }) { return <View style={styles.inputGroup}><Text style={styles.inputLabel}>{label}</Text><TextInput placeholderTextColor="#94A3B8" style={styles.input} {...props} /></View>; }
export function StatusBadge({ label, tone = "gray" }: { label: string; tone?: "gray" | "green" | "amber" | "red" | "blue" }) { const current = { gray: ["#F1F5F9", colors.muted], green: [colors.greenSoft, colors.green], amber: [colors.amberSoft, colors.amber], red: [colors.redSoft, colors.red], blue: [colors.blueSoft, colors.blue] }[tone]; return <View style={[styles.badge, { backgroundColor: current[0] }]}><Text style={[styles.badgeText, { color: current[1] }]}>{label}</Text></View>; }
export function Metric({ label, value, accent = colors.blue }: { label: string; value: string | number; accent?: string }) { return <View style={styles.metric}><Text style={[styles.metricValue, { color: accent }]}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
export function EmptyState({ icon = "inventory-2", title, detail }: { icon?: IconName; title: string; detail: string }) { return <View style={styles.empty}><MaterialIcons name={icon} size={40} color="#94A3B8" /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyDetail}>{detail}</Text></View>; }
export function Card({ children, style }: PropsWithChildren<{ style?: ViewStyle }>) { return <View style={[styles.card, style]}>{children}</View>; }
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.page }, fill: { flex: 1 }, scroll: { padding: 20, gap: 16, paddingBottom: 28 },
  header: { minHeight: 68, backgroundColor: colors.navy, paddingHorizontal: 20, paddingVertical: 13, flexDirection: "row", alignItems: "center" }, headerText: { flex: 1, alignItems: "flex-end" }, headerTitle: { color: "#FFFFFF", fontSize: 22, fontWeight: "800", writingDirection: "rtl" }, headerSubtitle: { color: "#C7D8EA", fontSize: 12, marginTop: 3, writingDirection: "rtl" }, headerAction: { minWidth: 42, alignItems: "flex-start" },
  primaryButton: { minHeight: 52, borderRadius: 14, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, paddingHorizontal: 18 }, primaryButtonText: { color: "#FFFFFF", fontWeight: "800", fontSize: 16, writingDirection: "rtl" }, secondaryButton: { minHeight: 48, borderRadius: 14, backgroundColor: colors.blueSoft, borderWidth: 1, borderColor: "#BFDBFE", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, paddingHorizontal: 16 }, secondaryButtonText: { color: colors.blue, fontWeight: "700", fontSize: 15, writingDirection: "rtl" }, disabled: { opacity: 0.55 }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  inputGroup: { gap: 7 }, inputLabel: { color: colors.slate, fontWeight: "700", fontSize: 14, textAlign: "right", writingDirection: "rtl" }, input: { minHeight: 52, borderWidth: 1, borderColor: colors.border, backgroundColor: "#FFFFFF", borderRadius: 13, paddingHorizontal: 14, color: colors.slate, fontSize: 16, textAlign: "right", writingDirection: "rtl" },
  badge: { borderRadius: 99, paddingHorizontal: 10, paddingVertical: 5, alignSelf: "flex-end" }, badgeText: { fontWeight: "800", fontSize: 12, writingDirection: "rtl" }, metric: { flex: 1, alignItems: "center", gap: 4, paddingVertical: 5 }, metricValue: { fontSize: 22, fontWeight: "900" }, metricLabel: { color: colors.muted, fontSize: 12, textAlign: "center", writingDirection: "rtl" },
  empty: { alignItems: "center", justifyContent: "center", padding: 28, gap: 9, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: "#FFFFFF" }, emptyTitle: { color: colors.slate, fontWeight: "800", fontSize: 16, writingDirection: "rtl" }, emptyDetail: { color: colors.muted, fontSize: 13, textAlign: "center", lineHeight: 20, writingDirection: "rtl" }, card: { backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 16 },
});

