import { useCallback, useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { AppScreen, EmptyState, PageHeader, PrimaryButton, StatusBadge, colors } from "@/components/mobile-ui";
import { type CachedInventoryRecord, displayResult, isCounted } from "@/features/assetx/domain";
import { getStoredSnapshot, queueInventoryMutation } from "@/features/assetx/offline-store";

export default function CycleInventoryScreen() {
  const router = useRouter(); const { cycleId } = useLocalSearchParams<{ cycleId: string }>(); const [records, setRecords] = useState<CachedInventoryRecord[]>([]); const [cycleTitle, setCycleTitle] = useState(""); const [query, setQuery] = useState(""); const [busyId, setBusyId] = useState<string | null>(null);
  const refresh = useCallback(async () => { const snapshot = await getStoredSnapshot(String(cycleId)); setRecords(snapshot?.records ?? []); setCycleTitle(snapshot ? `دورة جرد ${snapshot.cycle.year}` : "دورة غير محفوظة"); }, [cycleId]); useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); return normalized ? records.filter((record) => `${record.asset_name} ${record.asset_code}`.toLowerCase().includes(normalized)) : records; }, [query, records]); const counted = records.filter(isCounted).length;
  async function quickMatch(record: CachedInventoryRecord) { setBusyId(record.record_id); try { await queueInventoryMutation(String(cycleId), record.record_id, { actual_quantity: record.expected_quantity ?? 1 }); await refresh(); } catch { Alert.alert("تعذر حفظ النتيجة", "تأكد أن الدورة ما زالت محفوظة على هذا الهاتف ثم حاول مرة أخرى."); } finally { setBusyId(null); } }
  return <AppScreen><PageHeader title={cycleTitle} subtitle={`${counted} من ${records.length} تم تسجيلها`} action={<Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={25} color="#FFFFFF" /></Pressable>} /><View style={styles.toolbar}><TextInput value={query} onChangeText={setQuery} style={styles.search} placeholder="ابحث بالاسم أو كود الأصل" placeholderTextColor="#94A3B8" textAlign="right" /><PrimaryButton title="مسح" icon="qr-code-scanner" onPress={() => router.push({ pathname: "/scanner", params: { cycleId: String(cycleId) } })} /></View><FlatList data={filtered} contentContainerStyle={styles.list} keyExtractor={(item) => item.record_id} ListEmptyComponent={<EmptyState title="لا توجد سجلات مطابقة" detail="غيّر البحث أو نزّل الدورة من جديد." />} renderItem={({ item }) => <View style={styles.record}><View style={styles.recordTop}><StatusBadge label={item.sync_state === "pending" ? "بانتظار المزامنة" : item.sync_state === "conflict" ? "يحتاج مراجعة" : displayResult(item.result)} tone={item.sync_state === "pending" ? "amber" : item.sync_state === "conflict" ? "red" : isCounted(item) ? "green" : "gray"} /><Text style={styles.assetName}>{item.asset_name}</Text></View><Text style={styles.assetCode}>{item.asset_code || "بدون كود"}</Text><Text style={styles.location}>{item.expected_location_path ?? item.expected_location ?? "موقع غير محدد"}</Text><View style={styles.actions}><Pressable onPress={() => router.push(`/inventory/${cycleId}/record/${item.record_id}`)} style={({ pressed }) => [styles.detailButton, pressed && styles.pressed]}><Text style={styles.detailText}>تفاصيل</Text></Pressable>{!isCounted(item) ? <Pressable disabled={busyId === item.record_id} onPress={() => void quickMatch(item)} style={({ pressed }) => [styles.matchButton, busyId === item.record_id && styles.disabled, pressed && styles.pressed]}><MaterialIcons name="check" size={18} color="#FFFFFF" /><Text style={styles.matchText}>موجود هنا</Text></Pressable> : null}</View></View>} /></AppScreen>;
}
const styles = StyleSheet.create({ back: { padding: 8 }, toolbar: { padding: 16, gap: 10, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderBottomColor: colors.border }, search: { minHeight: 46, backgroundColor: "#F8FAFC", borderRadius: 12, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 13, color: colors.slate, writingDirection: "rtl" }, list: { padding: 16, gap: 12, flexGrow: 1 }, record: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: colors.border, borderRadius: 15, padding: 14, gap: 7 }, recordTop: { flexDirection: "row", justifyContent: "space-between", gap: 9 }, assetName: { flex: 1, color: colors.slate, fontSize: 16, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, assetCode: { color: colors.blue, fontWeight: "800", textAlign: "right" }, location: { color: colors.muted, textAlign: "right", writingDirection: "rtl" }, actions: { flexDirection: "row", gap: 9, marginTop: 3 }, detailButton: { minHeight: 40, borderRadius: 11, borderWidth: 1, borderColor: "#BFDBFE", backgroundColor: "#EFF6FF", paddingHorizontal: 15, alignItems: "center", justifyContent: "center" }, detailText: { color: colors.blue, fontWeight: "800", writingDirection: "rtl" }, matchButton: { flex: 1, minHeight: 40, borderRadius: 11, backgroundColor: colors.green, flexDirection: "row", gap: 5, alignItems: "center", justifyContent: "center" }, matchText: { color: "#FFFFFF", fontWeight: "800", writingDirection: "rtl" }, pressed: { opacity: 0.8 }, disabled: { opacity: 0.55 } });

