import { useCallback, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useRouter } from "expo-router";
import { AppScreen, Card, EmptyState, Metric, PageHeader, PrimaryButton, SecondaryButton, StatusBadge, colors } from "@/components/mobile-ui";
import { getCycles } from "@/features/assetx/api";
import { type InventoryCycle, displayCycleStatus, friendlyError } from "@/features/assetx/domain";
import { listPendingMutations, listStoredSnapshots } from "@/features/assetx/offline-store";
import { useSession } from "@/features/assetx/session-context";

export default function FieldScreen() {
  const router = useRouter(); const { user, backendUrl } = useSession(); const [cycles, setCycles] = useState<InventoryCycle[]>([]); const [downloadedCycleId, setDownloadedCycleId] = useState<string | null>(null); const [pending, setPending] = useState(0); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { setLoading(true); try { const [availableCycles, snapshots, mutations] = await Promise.all([getCycles(), listStoredSnapshots(), listPendingMutations()]); setCycles(availableCycles); setDownloadedCycleId(snapshots[0]?.cycle_id ?? null); setPending(mutations.length); setError(null); } catch (nextError) { setError(friendlyError(nextError)); const [snapshots, mutations] = await Promise.all([listStoredSnapshots(), listPendingMutations()]); setDownloadedCycleId(snapshots[0]?.cycle_id ?? null); setPending(mutations.length); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  const activeCycle = cycles.find((cycle) => cycle.id === downloadedCycleId) ?? cycles.find((cycle) => cycle.status === "in_progress") ?? cycles[0] ?? null;
  return <AppScreen scroll><PageHeader title="الميدان" subtitle={user ? `مرحباً ${user.username}` : ""} action={<Pressable onPress={() => void refresh()} style={styles.headerIcon}><MaterialIcons name="refresh" size={24} color="#FFFFFF" /></Pressable>} /><View style={styles.content}>
    <Card><View style={styles.connectionRow}><StatusBadge label={backendUrl ? "الإعداد محفوظ" : "الإعداد ناقص"} tone={backendUrl ? "green" : "amber"} /><Text style={styles.connectionTitle}>اتصال النظام</Text></View><Text style={styles.connectionUrl} numberOfLines={1}>{backendUrl ?? "لم يتم إدخال رابط Backend بعد"}</Text></Card>
    <Card><View style={styles.metrics}><Metric label="عمليات معلقة" value={pending} accent={pending ? colors.amber : colors.green} /><View style={styles.divider} /><Metric label="دورات محفوظة" value={downloadedCycleId ? 1 : 0} /><View style={styles.divider} /><Metric label="دورات متاحة" value={cycles.length} /></View></Card>
    {error ? <Card style={styles.warning}><Text style={styles.warningText}>{error}</Text><SecondaryButton title="محاولة التحديث" icon="refresh" onPress={() => void refresh()} /></Card> : null}
    {activeCycle ? <Card style={styles.cycleCard}><StatusBadge label={displayCycleStatus(activeCycle.status)} tone={activeCycle.status === "in_progress" ? "green" : activeCycle.status === "closed" ? "gray" : "blue"} /><Text style={styles.cycleTitle}>دورة جرد {activeCycle.year}</Text><Text style={styles.cycleDescription}>{downloadedCycleId === activeCycle.id ? "هذه الدورة محفوظة على الهاتف وجاهزة للعمل دون اتصال." : "نزّل الدورة إلى الهاتف قبل بدء الجرد الميداني."}</Text>{downloadedCycleId === activeCycle.id ? <PrimaryButton title="بدء العمل الميداني" icon="play-arrow" onPress={() => router.push(`/inventory/${activeCycle.id}`)} /> : <SecondaryButton title="عرض الدورات وتنزيلها" icon="download" onPress={() => router.push("/cycles")} />}</Card> : <EmptyState icon="assignment" title={loading ? "يجري تحميل الدورات" : "لا توجد دورة متاحة"} detail={loading ? "يتم التحقق من البيانات المتاحة لديك." : "أنشئ دورة جرد من منصة الويب أولاً، ثم حدّث هذه الشاشة."} />}
  </View></AppScreen>;
}
const styles = StyleSheet.create({ headerIcon: { padding: 8 }, content: { padding: 20, gap: 16 }, connectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 9 }, connectionTitle: { color: colors.slate, fontWeight: "800", fontSize: 16, writingDirection: "rtl" }, connectionUrl: { color: colors.muted, fontSize: 12, textAlign: "right" }, metrics: { flexDirection: "row", alignItems: "center" }, divider: { width: 1, height: 38, backgroundColor: colors.border }, warning: { gap: 12, backgroundColor: "#FFFBEB", borderColor: "#FDE68A" }, warningText: { color: "#92400E", textAlign: "right", lineHeight: 20, writingDirection: "rtl" }, cycleCard: { gap: 12 }, cycleTitle: { color: colors.slate, fontSize: 20, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, cycleDescription: { color: colors.muted, lineHeight: 21, textAlign: "right", writingDirection: "rtl" } });
