import { useCallback, useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import * as Network from "expo-network";
import { useFocusEffect } from "expo-router";
import { AppScreen, Card, EmptyState, Metric, PageHeader, PrimaryButton, StatusBadge, colors } from "@/components/mobile-ui";
import { listPendingMutations } from "@/features/assetx/offline-store";
import { syncPendingInventory, type SyncSummary } from "@/features/assetx/sync";

export default function SyncScreen() {
  const network = Network.useNetworkState(); const [pending, setPending] = useState(0); const [syncing, setSyncing] = useState(false); const [lastSummary, setLastSummary] = useState<SyncSummary | null>(null); const refresh = useCallback(async () => setPending((await listPendingMutations()).length), []); useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  async function handleSync() { setSyncing(true); try { const summary = await syncPendingInventory(); setLastSummary(summary); await refresh(); if (summary.conflicts > 0) Alert.alert("اكتملت المزامنة مع مراجعة", `تمت مزامنة ${summary.synced} عملية. توجد ${summary.conflicts} عملية تحتاج مراجعة.`); } catch { Alert.alert("تعذرت المزامنة", "حُفظت عملياتك على الهاتف. تحقق من Backend والاتصال ثم حاول مرة أخرى."); } finally { setSyncing(false); } }
  const online = network.isInternetReachable === true || network.isConnected === true;
  return <AppScreen scroll><PageHeader title="المزامنة" subtitle="أرسل العمل المحفوظ إلى نظام AssetX" /><View style={styles.content}><Card><View style={styles.statusRow}><StatusBadge label={online ? "شبكة متاحة" : "دون اتصال"} tone={online ? "green" : "amber"} /><Text style={styles.statusTitle}>حالة الشبكة</Text></View><Text style={styles.statusDetail}>{online ? "يمكنك إرسال العمليات عند جاهزية Backend." : "تابع العمل؛ لن تضيع النتائج وستُرسل لاحقاً."}</Text></Card><Card><View style={styles.metricRow}><Metric label="عمليات معلقة" value={pending} accent={pending ? colors.amber : colors.green} /><View style={styles.divider} /><Metric label="آخر مزامنة" value={lastSummary ? lastSummary.synced : "—"} /></View></Card>{pending > 0 ? <PrimaryButton title={`مزامنة ${pending} عملية`} icon="sync" loading={syncing} disabled={!online || syncing} onPress={() => void handleSync()} /> : <EmptyState icon="cloud-done" title="لا توجد عمليات معلقة" detail="كل ما هو محفوظ على الهاتف متزامن حالياً أو لا توجد نتائج جرد جديدة." />}{lastSummary ? <Card><Text style={styles.summaryTitle}>نتيجة آخر محاولة</Text><View style={styles.summaryRow}><Metric label="تم إرسالها" value={lastSummary.synced} accent={colors.green} /><Metric label="تحتاج مراجعة" value={lastSummary.conflicts} accent={lastSummary.conflicts ? colors.red : colors.muted} /><Metric label="بقيت معلقة" value={lastSummary.pending} accent={lastSummary.pending ? colors.amber : colors.muted} /></View></Card> : null}</View></AppScreen>;
}
const styles = StyleSheet.create({ content: { padding: 20, gap: 16 }, statusRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 9 }, statusTitle: { color: colors.slate, fontSize: 16, fontWeight: "800", writingDirection: "rtl" }, statusDetail: { color: colors.muted, textAlign: "right", lineHeight: 20, writingDirection: "rtl" }, metricRow: { flexDirection: "row", alignItems: "center" }, divider: { height: 40, width: 1, backgroundColor: colors.border }, summaryTitle: { color: colors.slate, fontWeight: "900", textAlign: "right", writingDirection: "rtl", marginBottom: 10 }, summaryRow: { flexDirection: "row" } });

